apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
spec:
  version: ${es_version}
  count: ${entsearch_pod_count}
  elasticsearchRef:
    name: eck-elasticsearch
  config:
    ##testing how to add app search UI, this seems to work
    #kibana.host: https://whfvxwgqcqispuzv.eastus.cloudapp.azure.com:5601
    #ent_search.external_url: https://ablkjasdlifjas.eastus.cloudapp.azure.com:3002
    #elasticsearch.username: "elastic"
    #elasticsearch.password: "xxxx"
  configRef:
    secretName: es-credentials
  podTemplate:
    metadata:
      labels:
        acceptIngest: "${entsearch_accept_ingest}"
        acceptSearch: "${entsearch_accept_search}"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodetype
                operator: In
                values:
                - entsearch
      containers:
      - name: enterprise-search
        resources:
          requests:
            cpu: ${entsearch_pod_cpu}
            memory: ${entsearch_pod_memory}
        env:
        - name: JAVA_OPTS
          value: ${entsearch_pod_ES_JAVA_OPTS}
  ###commented out as this is generally not used.  This is for the app search ui
  # http:
  #  service:
  #   metadata:
  #        annotations:
  #           service.beta.kubernetes.io/azure-dns-label-name: "ablkjasdlifjas"
  #   spec:
  #        type: LoadBalancer
  #  tls:
  #   selfSignedCertificate:
  #    subjectAltNames:
  #    - dns: "*.cloudapp.azure.com"
